services:
  postgres:
    image: postgres:15.5
    container_name: tt_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  rest:
    container_name: tt_rest
    depends_on:
      - postgres
    ports:
      - ${REST_PORT}:${REST_PORT}
    build:
      context: task-tracker-backend
      dockerfile: Dockerfile.rest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      API_PORT: ${REST_PORT}
  front:
    container_name: tt_front
    ports:
      - ${FRONT_PORT}:5173
    build:
      context: task-tracker-frontend
    environment:
      PORT: ${FRONT_PORT}
volumes:
  postgres_data:

