spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/task_tracker_db}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:234}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
    show-sql: true
    open-in-view: false
server:
  ip: ${SERVER_IP:localhost}
  port:
    ${API_PORT:8080}
api-version:
  "v1"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ".log"

