spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: registration-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        value:
          deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          default.type: com.tasktracker.dto.MessageDto
  mail:
    host: ${EMAIL_SERVICE_HOST}
    port: ${EMAIL_SERVICE_PORT}
    username: ${EMAIL_SERVICE_USERNAME}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ".log"